### ISSUE TITLE
Any-length delimiters?

### ISSUE THREAD

**Issue by spiderpete** [spullara/mustache.java#227] opened 2019-02-04 18:37 UTC
Mustache seems quite flexible when it comes to the user defining their own tag delimiters. However, it stops rendering the inputs as expected if the delimiter's length exceeds 2 character, e.g.

Tag mapping: "tag" -> "substitution"

1. Case 1: OK
   * Start delimiter: "++"
   * End delimiter: "++"
   * Input: "This is the ++tag++ that should work."
   * Expected output: "This is the substitution that should work."
   * Actual output: "This is the substitution that should work."

1. Case 2: Wrong - does not replace, one more delimiter character on either side
   * Start delimiter: "+++"
   * End delimiter: "+++"
   * Input: "This is the +++tag+++ that should work."
   * Expected output: "This is the substitution that should work."
   * Actual output: "This is the ++++tag++++ that should work."

1. Case 3: Wrong - does replace, but leftover from end delimiter
   * Start delimiter: "++"
   * End delimiter: "+++"
   * Input: "This is the ++tag+++ that should work."
   * Expected output: "This is the substitution that should work."
   * Actual output: "This is the substitution+ that should work."

1. Case 4: Wrong - does not replace
   * Start delimiter: "+++"
   * End delimiter: "++"
   * Input: "This is the +++tag++ that should work."
   * Expected output: "This is the substitution that should work."
   * Actual output: "This is the +++tag++ that should work."

1. Case 5: Wrong - does replace, but should not because the delimiters are not present in the input in full length
   * Start delimiter: "+++"
   * End delimiter: "+++"
   * Input: "This is the ++tag++ that should work."
   * Expected output: "This is the ++tag++ that should work."
   * Actual output: "This is the substitution that should work."

There are no docs on the method accepting customized delimiters `Mustache compile(Reader reader, String file, String sm, String em)`. Are there any intended restrictions on the tags' delimiters or are the above cases supposed to be rendered as expected?

**Comment by spullara** [comment] 2019-02-25 19:38
Here is the specification for delimiters:

```
Set Delimiter tags are used to change the tag delimiters for all content
  following the tag in the current compilation unit.
  The tag's content MUST be any two non-whitespace sequences (separated by
  whitespace) EXCEPT an equals sign ('=') followed by the current closing
  delimiter.
```

https://github.com/mustache/spec/blob/master/specs/delimiters.yml

**Comment by spullara** [comment] 2019-02-27 20:53
I'm going to close this as longer delimiters aren't in the specification and this is not a bug.

**Closed by spullara** 2019-02-27 20:53 UTC
